### ISSUE TITLE
Add hint for IPv6 only machines

### ISSUE THREAD

**Issue by KastenKlicker** [PaperMC/docs#342]
The `-Djava.net.preferIPv6Addresses=true` flag must be present on IPv6 only machines when first starting a paper server or otherwise it will fail to download the vanilla server file.

This is a good hint for all newbies, which should be present in the paper Getting Started docs.

I can add some IPv6 docs myself as I'm setting up velocity and paper on an IPv6 only machine at the moment.
If someone can tell me where to put them, I would be happy to help ;)

**Comment by Nacioszeczek** [comment]
This is a bug that should be fixed in Paper then (and Java in general), not docs made for it.
If this is still occurring please [open an issue in Paper](https://github.com/PaperMC/Paper/issues/new/choose) with appropriate logs and mention this issue there.

see 
[here for a possible fix](https://canary.discord.com/channels/289587909051416579/947676006964162611/1261210505973071921)
[JDK-8016521](https://bugs.openjdk.org/browse/JDK-8016521)
[JDK-8179037](https://bugs.openjdk.org/browse/JDK-8179037)
